source 'https://gems.ruby-china.org'

ruby "2.3.0"

gem 'rails', '~> 4.2.6'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

gem 'jbuilder', '~> 1.0.1'

group :development do
  gem 'sqlite3'
end

group :doc do
  gem 'sdoc', require: false
end
